.\" PER KEN (3/29/17), LUMINA-DESKTOP MANPAGE SHOULD REDIRECT TO
.\" START-LUMINA-DESKTOP MANPAGE. FILL EMPTY PAGE IN LATER.
.Dd March 29, 2017
.Dt LUMINA-DESKTOP 8
.Os TrueOS Rolling Release
.\"-------------------------------------------------------------------
.Sh NAME
.Nm lumina-desktop
.Nd Binary used to run the desktop.
.\"-------------------------------------------------------------------
.Sh SYNOPSIS
.Nm
.Cm <file>
.\" NEEDS EXPANSION!!!!!!!!!!!
.\"-------------------------------------------------------------------
.Sh DESCRIPTION
The
.Nm
utility <CONTINUE DESCRIPTION>
.Pp
Here are the
.Nm
options:
.Pp
.Bl -tag -width indent
.It Ic <option1>
.It Ic <option2>
.El
.\"-------------------------------------------------------------------
.Sh EXAMPLES
.Bl -tag -width indent
.It example1
ex1 description.
.Pp
.It example2
ex2 description.
.El
.\"-------------------------------------------------------------------
.Sh FILES
.Bl -tag -width indent
.It Pa /file1
Description1
.It Pa /file2
Description2
.El
.\"-------------------------------------------------------------------
.Sh SEE ALSO
.Xr
.Xr
.\"-------------------------------------------------------------------
.Sh AUTHOR
.An Tim Moore
.Aq timmoore88@gmail.com
