.Dd March 29, 2017
.Dt LUMINA-OPEN 8
.Os TrueOS Rolling Release
.\"-------------------------------------------------------------------
.Sh NAME
.Nm lumina-open
.Nd Application launcher for the Lumina Desktop Environment.
.\"-------------------------------------------------------------------
.Sh SYNOPSIS
.Nm
.Pp
.Nm
.Cm [-select] | [-action <ActionID>] | <absolute file path or URL>
.Pp
.Nm
.Cm [-volumeup | -volumedown | -brightnessup | -brightnessdown]
.\"-------------------------------------------------------------------
.Sh DESCRIPTION
Given a file with an absolute pathway or URL, the
.Nm
utility finds the appropriate application which which to open the 
file. If the file is a *.desktop application shortcut,
.Nm
starts the application automatically. Using the appropriate flags 
allows
.Nm
to perform a few specific system operations. Here are the commands, 
flags, and descriptions of their functionality:
.Pp
.Bl -tag -width indent
.It Ic <option1>
.It Ic <option2>
.El
.\"-------------------------------------------------------------------
.Sh EXAMPLES
.Bl -tag -width indent
.It example1
ex1 description.
.Pp
.It example2
ex2 description.
.El
.\"-------------------------------------------------------------------
.Sh FILES
.Bl -tag -width indent
.It Pa /file1
Description1
.It Pa /file2
Description2
.El
.\"-------------------------------------------------------------------
.Sh SEE ALSO
.Xr
.Xr
.\"-------------------------------------------------------------------
.Sh AUTHOR
.An Tim Moore
.Aq timmoore88@gmail.com
